// <auto-generated />
using System;
using Com.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.Repo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190406173037_updateUserUnilever")]
    partial class updateUserUnilever
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Data.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<Guid>("Creator");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid>("Modifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce59a858-d20e-4d7b-8207-23b912190181"),
                            AddedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "classic",
                            Creator = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Description = "Offers the most basic level of advertisement",
                            ModifiedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modifier = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Name = "Classic Ad",
                            Price = 269.99000000000001
                        },
                        new
                        {
                            Id = new Guid("42b323f6-4b1f-449e-894d-3ee3c181fbf9"),
                            AddedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "standout",
                            Creator = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Description = "Allows advertisers to use a company logo and use a longer presentation text",
                            ModifiedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modifier = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Name = "Standout Ad",
                            Price = 322.99000000000001
                        },
                        new
                        {
                            Id = new Guid("88d45054-b3f7-4c64-aaaa-00cc6f063ed0"),
                            AddedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "premium",
                            Creator = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Description = "Same benefits as Standout Ad, but also puts the advertisement at the top of the results, allowing higher visibility",
                            ModifiedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modifier = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Name = "Premium Ad",
                            Price = 394.99000000000001
                        });
                });

            modelBuilder.Entity("Com.Data.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("BelongsTo");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("Creator");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid>("Modifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.HasIndex("BelongsTo", "Type")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b4ae92f-0be3-4fb6-9177-c50686c748b7"),
                            AddedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddressLine1 = "Something here",
                            AddressLine2 = "Something there",
                            BelongsTo = new Guid("8a75c7fe-d6af-4ee3-ba51-06c26b794080"),
                            City = "Putra Jaya",
                            Country = "Malaysia",
                            Creator = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            ModifiedDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modifier = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            State = "Selangor",
                            Type = (short)2
                        });
                });

            modelBuilder.Entity("Com.Data.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AddressTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("Com.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<Guid>("Creator");

                    b.Property<string>("Email")
                        .HasMaxLength(25);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid>("Modifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(240);

                    b.Property<short>("Type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a75c7fe-d6af-4ee3-ba51-06c26b794080"),
                            AddedDate = new DateTime(2019, 4, 7, 1, 30, 36, 375, DateTimeKind.Local).AddTicks(5867),
                            Creator = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Email = "unilever@yahoo.com",
                            FirstName = "Unilever",
                            LastName = "",
                            ModifiedDate = new DateTime(2019, 4, 7, 1, 30, 36, 376, DateTimeKind.Local).AddTicks(6333),
                            Modifier = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            Password = "$MYHASH$V1$10000$xcFsnGmPpBute45y3p6bGanZvI3JLuPRJGUZopaGHu1mMrPQ",
                            Type = (short)2,
                            UserName = "amer"
                        },
                        new
                        {
                            Id = new Guid("45e231ce-1a79-4289-9fe6-b89b66ef9d5f"),
                            AddedDate = new DateTime(2019, 4, 7, 1, 30, 36, 376, DateTimeKind.Local).AddTicks(8071),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "admin@yahoo.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            ModifiedDate = new DateTime(2019, 4, 7, 1, 30, 36, 376, DateTimeKind.Local).AddTicks(8078),
                            Modifier = new Guid("00000000-0000-0000-0000-000000000000"),
                            Password = "$MYHASH$V1$10000$xcFsnGmPpBute45y3p6bGanZvI3JLuPRJGUZopaGHu1mMrPQ",
                            Type = (short)1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Com.Data.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
